config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :users
  resources :tickets

  root "home#index"

  get "get-orders", to: "orders#get_orders"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :ticket
  belongs_to :user

  validates :user_id, presence: true
  validates :ticket_id, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :order

  validates :name, presence: true
  validates :price, presence: true
  validates :date, presence: true
  validates :taxe, presence: true

  def self.all_valids
    Ticket.where("date >= ?", Time.current).order(:date)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true

  def self.find_or_create params
    user = User.find_by(email: params[:email])
    return user if user.present?
    User.create params #not cool
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tickets = Ticket.all_valids
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:show]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  def get_orders
    email = params[:email]
    orders = User.find_by(email: email).try(:orders)
    tickets = orders.nil? ? "false" : orders.map{|o| o.ticket}.to_json
    render :json => { :product => tickets.to_json }
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @user = User.find_or_create user_params_for_order

    ticket_id = params[:ticket_id]

    @order = Order.new(ticket_id: ticket_id, user: @user)

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_path, notice: 'Pedido realizado com sucesso, foi enviado um e-mail com o boleto.' }
        format.json { render :show, status: :created, location: @order }
      else
        flash[:error] = "Não foi possível criar ou verificar o usuário, tente novamente."
        format.html { redirect_to root_path }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def check_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status, :ticket_id, :user_id)
    end

    def user_params_for_order
      params.require(:user).permit(:name, :email, :phone)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to root_path, notice: 'Evento criado com sucesso.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        flash[:error] = "Os seguinte erros foram encontrados:" + @ticket.errors.full_messages.to_sentence
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :price, :date, :taxe)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= render "tickets/index", tickets: @tickets%>

app/views/layouts/_footer.html.erb
<div class="row">
	<div class="col-sm-6 col-sm-offset-3 text-center">
		Desenvolvido por Matheus Kemer
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <!--
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" >iTicket</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params["controller"] == "home"%>"><a href="/">Eventos</a></li>
        <li class="<%= 'active' if params["controller"] == "orders"%>"><a href="/orders">Meus pedidos</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </div>
  </div>
  -->
  <div class="menu">
    <p class="title"><strong> iTicket </strong></p>
    <p class="subtitle"> <strong>você</strong> vai onde a <strong>diversão</strong> está </p>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iTicket</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
    <script src="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/v4.0.0/src/js/bootstrap-datetimepicker.js"></script>
    <link href="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/v4.0.0/build/css/bootstrap-datetimepicker.css" rel="stylesheet" />
  </head>

  <body>
    <%= render "layouts/header"%>
    <% flash.each do |key, value| %>
       <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> text-center"><%= value %></div>
     <% end %>
    <div class="container">
      <div class="nav-items text-center">
        <%= link_to "Eventos", root_path,
          class: "nav-item-left #{'active' if params["controller"] == 'home'}" %>
        |
        <%= link_to "Pedidos", orders_path,
          class: "nav-item-right #{'active' if params["controller"] == 'orders'}" %>
      </div>
      <%= yield %>
      <br /><br />
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="field">
    <%= f.label :ticket_id %>
    <%= f.text_field :ticket_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

<%= button_to 'Voltar', root_path, method: :get, class: "btn btn-danger" %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="row">
	<div class="form-group user-email col-sm-offset-3 col-sm-6">
	  <p class="text-center">Digite seu e-mail</p>
	  <input type="text" id="email" class="form-control">
	  <br />
	  <input type="submit" value="Visualizar" onClick="getTickets()" class="btn btn-primary center-block">
	</div>
</div>

<div class="row">
	<div class="col-sm-8 col-sm-offset-2" id="responseTable">
	</div>
</div>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket:</strong>
  <%= @order.ticket.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user.name %>
</p>

<%= link_to 'Back', orders_path %>

app/views/tickets/_form.html.erb
<%= form_for(ticket, :html => {:class => ''}) do |f| %>
  <div class="form-group row">
    <%= f.label "Nome do evento", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control', placeholder: "Nome do evento" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label "Valor  ", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, class: 'form-control price-field', placeholder: "00,00" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label "Data do evento", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :date, id: "datetimepicker", class: 'form-control', placeholder: "Data do evento" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label "Taxa", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.number_field :taxe, class: "form-control price-field", placeholder: "00,00" %>
    </div>
  </div>

  <div class="">
    <%= f.submit "Salvar", class: "btn btn-success pull-right" %>
  </div>
<% end %>

<script type="text/javascript">
    $('#datetimepicker').datetimepicker({format: 'DD-MM-YYYY hh:mm'});
</script>

app/views/tickets/_index.html.erb
<div class="nav-itens text-center">
  <div class="row events">
    <% if tickets && tickets.any? %>
        <% tickets.each do |ticket| %>
          <%#= link_to ticket_path(ticket) do%>
          <a href="#buyTicketModal<%=ticket.id%>" data-toggle="modal" data-target="#buyTicketModal<%=ticket.id%>">
            <div class="col-sm-4 one-ticket">
              <img src="Evento<%=(1..4).to_a.sample%>.png" class="img-responsive" style="width:100%" alt="Image">
              <strong>
                <p><%= ticket.name %></p>
                <p><%= ticket.date.strftime("%d/%m/%Y") %></p>
                <p>R$ <%= ticket.price + ticket.taxe %></p>
              </strong>
            </div>
          </a>
          <%# end %>
          <% @ticket = ticket%>
          <div id="buyTicketModal<%=ticket.id%>" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Mais informações</h4>
                </div>
                <div class="modal-body">
                  <%= render "tickets/show"%>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    <% else %>
      <div class="empty">
        <p> Não há eventos disponíveis, ainda </p>
      </div>
    <% end %>
  </div>
  <%= button_to("Novo Evento", new_ticket_path, method: :get, :class => "btn btn-primary") %>
</div><br>

app/views/tickets/_show.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-4 sidenav">
      <img src="Evento<%=(1..4).to_a.sample%>.png" class="img-responsive" style="width:100%" alt="Image">
    </div>

    <div class="col-md-8">
      <div class="event-info">
        <p class="title">
          <%= @ticket.name %>
        </p>

        <p>
          <strong>Valor:</strong>
          <%= @ticket.price %>
        </p>

        <p>
          <strong>Dia do evento:</strong>
          <%= @ticket.date.strftime("%d/%m/%Y - %H:%M") %>
        </p>

        <p>
          <strong>Taxa:</strong>
          <%= @ticket.taxe %>
        </p>

        <%= button_to "Quero ir", {}, {data: { target: "#buy-option#{@ticket.id}", toggle: :collapse },
                                      remote: true, class: 'btn btn-success buy-ticket'}  %>
      </div>
      <br />
    </div>
  </div>
  <div class="row content">
    <div class="buy-option" id="buy-option<%=@ticket.id%>">
      <p>Preencha o cadastro abaixo: </p>
      <%= render "users/form", user: User.new, ticket_id: @ticket.id %>
      <br />
    </div>
  </div>
</div>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/new.html.erb
<div class="row new-event">
  <h1 class="text-center">Novo evento</h1>
  <div class="col-sm-8 col-sm-offset-2">
  	<%= render 'form', ticket: @ticket %>
	</div>
</div>

app/views/tickets/show.html.erb
<div>
  <p>
    <strong>Nome:</strong>
    <%= @ticket.name %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= @ticket.price %>
  </p>

  <p>
    <strong>Dia do evento:</strong>
    <%= @ticket.date.strftime("%d/%m/%Y - %H:%M") %>
  </p>

  <p>
    <strong>Taxa:</strong>
    <%= @ticket.taxe %>
  </p>

  <%= button_to "Quero ir", {}, {onclick: "enableBuyOptions()", remote: true, class: 'btn btn-success buy-ticket'}  %>
</div>
<br />
<div class="buy-option">
  Preencha o cadastro abaixo:
  <%= render "users/form", user: User.new, ticket_id: @ticket.id %>
  <br />
</div>

<%= link_to "Back", root_path %>

app/views/users/_form.html.erb
<div class="text-center modal-form">
  <%= form_for :user, :url => orders_path, :method => "post" do |f| %>
    <%= hidden_field_tag "ticket_id", ticket_id if ticket_id.present? %>

    <div class="form-group row col-sm-8">
      <%= f.label :name, "Nome", class: "col-sm-12 col-form-label" %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group row col-sm-8">
      <%= f.label :email, class: "col-sm-12 col-form-label" %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group row col-sm-8">
      <%= f.label :phone, "Telefone", class: "col-sm-12 col-form-label" %>
      <%= f.text_field :phone, class: 'form-control' %>
    </div>

    <div class="form-group row col-sm-8">
      <%= f.submit "Comprar", class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>